# Generated by Django 3.0.8 on 2020-12-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.TextField(max_length=500)),
                ('second_line', models.TextField(max_length=500)),
                ('third_line', models.TextField(max_length=500)),
                ('fourth_line', models.TextField(max_length=500)),
            ],
        ),
    ]
