# Generated by Django 3.0.8 on 2020-11-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activation_amount',
            field=models.FloatField(default=0),
        ),
    ]
