# Generated by Django 3.0.8 on 2020-11-22 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Direct_Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=60)),
                ('activated_id', models.CharField(default='', max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='All_Level_Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=60)),
                ('activated_id', models.CharField(default='', max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('level', models.CharField(default='', max_length=10)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='All_Rank_Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('rank', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='All_Roi_Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fund_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=60)),
                ('activated_id', models.CharField(default='', max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Requested_Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('date', models.DateField(default='1999-01-01')),
                ('fund', models.FloatField(default=0)),
                ('transection_no', models.FloatField(default=0)),
                ('proof', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('status', models.CharField(default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_9_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_date', models.DateField(auto_now_add=True)),
                ('day', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_8_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_date', models.DateField(auto_now_add=True)),
                ('day', models.IntegerField(default=90)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_7_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_date', models.DateField(auto_now_add=True)),
                ('day', models.IntegerField(default=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_6_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_date', models.DateField(auto_now_add=True)),
                ('day', models.IntegerField(default=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_5_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_date', models.DateField(auto_now_add=True)),
                ('day', models.IntegerField(default=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_4_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_date', models.DateField(auto_now_add=True)),
                ('day', models.IntegerField(default=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_3_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_date', models.DateField(auto_now_add=True)),
                ('day', models.IntegerField(default=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_2_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_date', models.DateField(auto_now_add=True)),
                ('day', models.IntegerField(default=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_1_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_date', models.DateField(auto_now_add=True)),
                ('day', models.IntegerField(default=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_10_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_date', models.DateField(auto_now_add=True)),
                ('day', models.IntegerField(default=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_fund', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(default='-', max_length=40)),
                ('account_number', models.CharField(default='-', max_length=30)),
                ('branch_name', models.CharField(default='-', max_length=40)),
                ('ifsc_code', models.CharField(default='-', max_length=20)),
                ('bank_name', models.CharField(default='-', max_length=30)),
                ('nominee_name', models.CharField(default='-', max_length=30)),
                ('aadhar_number', models.CharField(default='-', max_length=12)),
                ('pan_number', models.CharField(default='-', max_length=10)),
                ('aadhar_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='adhar_pics')),
                ('pan_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pan_pics')),
                ('p_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('cheak', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
